### ISSUE TITLE
google - twitter login app ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#579] opened 2018-01-20 07:13 UTC
can we get an app for google and twitter - signups - logins ? I dont really use facebook but do use twitter and google plus

**Comment by neil96** [comment] 2018-01-22 02:17
Duplicate of #417

For twitter signups/logins, please open a new request. Thanks.

**Closed by neil96** 2018-01-22 02:17 UTC
