### ISSUE TITLE
Option to Enable/disable the "Recently active" 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#144] opened 2016-05-21 19:13 UTC
Hello :) 

its awesome that phpfox has got the option to hide the "users you may know" , 

but if there was an option to disable the "Recently active" to work along side it, that'd be better :)

**Comment by neil96** [comment] 2018-01-18 08:25
Duplicate of #482

**Closed by neil96** 2018-01-18 08:25 UTC
Labels: Under review
