### ISSUE TITLE
Add current indicators in the market place

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-feature-requests#694] opened 2018-07-27 20:34 UTC
It would be great to have indicators that let you know if you've already installed the app and the your version vs the current version when you are looking at apps. See image below for example

![screenshot](https://user-images.githubusercontent.com/19594886/43345313-f99cacd6-91ba-11e8-8687-67f2dec32863.png)

**Comment by spirogg** [comment] 2018-07-29 10:19
@prepperz look at this one they accepted  #578 smart brains think alike. :)

**Comment by neil96** [comment] 2018-07-31 07:19
Duplicate of #578

**Closed as completed by neil96** 2018-07-31 07:19 UTC
