### ISSUE TITLE
Incorrect website encoding for php 7.1.22

### ISSUE THREAD

**Issue by websistema1** [PHPfox-Official/phpfox-v4-feature-requests#745] opened 2018-11-04 17:04 UTC
I use Russian and Ukrainian language packages on the site. I now have a version of php 5.6.36 installed on the server. php 7.1.22 does not support the mysql extension, but only mysqli, that is, in the configuration file /PF.Base/file/settings/server.sett.php instead of $ _CONF ['db'] ['driver'] = 'MySQL'; it was necessary to register $ _CONF ['db'] ['driver'] = 'mysqli'; - the error disappears, and the site begins work on a new version of php 7.1.22. But I was not happy for a long time, since almost the entire text began to appear in the wrong encoding. See the screenshot. I started changing the encodings in the database and in other places, but nothing helped. If I switch back to php 5.6.36, the site works with normal encoding and without errors. Tell me, how can I get the site to display the correct encoding on php 7.1.22?
https://community.phpfox.com/forum/thread/57547/incorrect-website-encoding-for-php-7-1-22/

**Comment by spirogg** [comment] 2018-11-05 07:12
https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2419

**Comment by harrison05** [comment] 2018-11-09 02:41
Duplicate of https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2419

**Closed as completed** 2018-11-09 02:41 UTC
