### ISSUE TITLE
Add featured threads to forums

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-feature-requests#739] opened 2018-10-20 13:59 UTC
Adding featured threads to forum will be awesome.

**Comment by harrison05** [comment] 2018-10-22 02:39
Duplicate of #698

**Comment by harrison05** [comment] 2018-10-22 02:43
Currently, we don't have plan to implement this feature, you can use "Sticky" on a thread to make it stick on top.

Regards.

**Closed as completed** 2018-11-05 06:42 UTC
Labels: duplicate
