### ISSUE TITLE
edit: can we just add libfdk-aac  for encoding in Video App The best AAC encoder to use is libfdk_aac

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#647] opened 2018-04-17 09:22 UTC
Hi FEATURE REQUEST 
You would need to compile FFmpeg configured with options including "--enable-nonfree --enable-libfdk-aac".
but The best AAC encoder to use is libfdk_aac, the Fraunhofer FDK AAC codec library. FFMpeg supports encoding with it.

 

**hi can we just add libfdk_aac encoding in Video App

 
I tried and changed to below and its working better quality encoding please**

**this is OLD** 
/public_html/PF.Site/Apps/core-videos/Job/Encode.php
EDIT 
/public_html/PF.Site/Apps/core-videos/Job/Encode.php   you will find this around = line 151 thru 164

$videoCommand .= '-vcodec libx264' . ' '
            . '-acodec aac' . ' '             
            . '-strict experimental' . ' '
            . '-preset fast' . ' '
            . '-f mp4' . ' ';                        
 

**This is NEW - works flawless..** 
EDIT 
/public_html/PF.Site/Apps/core-videos/Job/Encode.php   you will find this around = line 151 thru 164

$videoCommand .= '-vcodec libx264' . ' '
            . '-acodec libfdk_aac' . ' '                      
            . '-strict experimental' . ' '
            . '-preset fast' . ' '
            . '-f mp4' . ' ';                        

 **better quality same speed just better encoding** - I don't want to have to edit every-time we upgrade 

can you just make it the default.  its the better option anyway please.

thanks,

Spiro

**Comment by neil96** [comment] 2018-04-17 09:24
Duplicate of #358

**Comment by spirogg** [comment] 2018-04-17 10:08
how about can we add libfdk_aac or option to add aac - libfdk_aac

**Closed as completed** 2018-04-27 05:13 UTC
